import eslint from '@eslint/js';
import tseslint from 'typescript-eslint';
import prettier from 'eslint-config-prettier';

export default tseslint.config(
  {
    ignores: [
      '**/dist/**',
      '**/node_modules/**',
      '**/coverage/**',
      '**/.next/**',
      // Generated by Next.js; its triple-slash references are not ours to fix.
      '**/next-env.d.ts',
      '.turbo/**',
      '.a5c/**',
      'extraction-inbox/**',
      // Synthetic fixture repo — data for the retrieval evals, not our source.
      '**/evals/fixtures/repo/**',
    ],
  },
  eslint.configs.recommended,
  ...tseslint.configs.recommended,
  {
    // Plain-JS test fixtures and dev-harness scripts run under Node.
    files: ['**/test/fixtures/**/*.mjs', '**/scripts/**/*.mjs'],
    languageOptions: {
      globals: {
        process: 'readonly',
        console: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        Buffer: 'readonly',
        URL: 'readonly',
        fetch: 'readonly',
      },
    },
  },
  prettier,
);
