import { sql } from 'drizzle-orm';
import {
  check,
  index,
  integer,
  jsonb,
  pgTable,
  text,
  timestamp,
} from 'drizzle-orm/pg-core';

/**
 * Postgres schema (drizzle-orm pg-core). Migrations are generated by
 * drizzle-kit (`pnpm --filter @patchback/api db:generate`) and committed
 * under `migrations/`.
 *
 * CHECK constraints mirror the runtime validators: they are the database's
 * own last line of defense for the trust tier and the canonical job states.
 * Row → domain mapping in store.ts revalidates anyway (fail closed).
 */

export const feedback = pgTable(
  'feedback',
  {
    id: text('id').primaryKey(),
    message: text('message').notNull(),
    trustTier: text('trust_tier').notNull(),
    submitter: jsonb('submitter'),
    capture: jsonb('capture'),
    triage: jsonb('triage'),
    threadId: text('thread_id'),
    inReplyTo: text('in_reply_to'),
    readTokenHash: text('read_token_hash').notNull(),
    createdAt: timestamp('created_at', {
      withTimezone: true,
      mode: 'date',
    }).notNull(),
    updatedAt: timestamp('updated_at', {
      withTimezone: true,
      mode: 'date',
    }).notNull(),
  },
  (table) => [
    index('feedback_thread_id_idx').on(table.threadId),
    check(
      'feedback_trust_tier_check',
      sql`${table.trustTier} in ('owner', 'insider', 'outsider')`,
    ),
  ],
);

export const jobs = pgTable(
  'jobs',
  {
    id: text('id').primaryKey(),
    feedbackId: text('feedback_id')
      .notNull()
      .references(() => feedback.id),
    state: text('state').notNull(),
    history: jsonb('history').notNull(),
    issueNumber: integer('issue_number'),
    branchName: text('branch_name'),
    prNumber: integer('pr_number'),
    prUrl: text('pr_url'),
    userSummary: text('user_summary'),
    previewUrl: text('preview_url'),
    error: text('error'),
    createdAt: timestamp('created_at', {
      withTimezone: true,
      mode: 'date',
    }).notNull(),
    updatedAt: timestamp('updated_at', {
      withTimezone: true,
      mode: 'date',
    }).notNull(),
  },
  (table) => [
    index('jobs_feedback_id_idx').on(table.feedbackId),
    index('jobs_pr_number_idx').on(table.prNumber),
    index('jobs_branch_name_idx').on(table.branchName),
    check(
      'jobs_state_check',
      sql`${table.state} in (
        'feedback.received', 'feedback.triaged', 'feedback.needs_clarification',
        'issue.created', 'patch.queued', 'patch.running', 'patch.failed',
        'patch.generated', 'pr.opened', 'pr.reviewed', 'patch.shipped',
        'feedback.closed'
      )`,
    ),
  ],
);
